# ----------------------------
# Makefile Options
# ----------------------------

NAME = TICHESS
ICON = icon.png
DESCRIPTION = "Play a simple version of chess on your TI-84 CE"
COMPRESSED = YES
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

MAKE_GFX = cd $(GFXDIR) && $(CONVIMG)

# ----------------------------

include $(shell cedev-config --makefile)